cars = [
    {
        'id': 0,
        'type': 'легковые',
        'brand': 'Toyota',
        'name': 'Corolla',
        'year': 2018,
        'price': 2500000,
        'distance': 100000,
        'color': 'black',
        'image': 'car1'
    },
    {
        'id': 1,
        'type': 'спортивные',
        'brand': 'Haval',
        'name': 'Corolla',
        'year': 2020,
        'price': 3500000,
        'distance': 50000,
        'color': 'purple',
        'image': 'car2'
    },
    {
        'id': 2,
        'type': 'внедорожники',
        'brand': 'Toyota',
        'name': 'Camri',
        'year': 2022,
        'price': 4000000,
        'distance': 150000,
        'color': 'green',
        'image': 'car1'
    },
    {
        'id': 3,
        'type': 'пикапы',
        'brand': 'Volkswagen',
        'name': 'Polo',
        'year': 2015,
        'price': 12500000,
        'distance': 50000,
        'color': 'gray',
        'image': 'car3'
    },
    {
        'id': 4,
        'type': 'минивены',
        'brand': 'Subaru',
        'name': 'Corolla',
        'year': 2017,
        'price': 3000000,
        'distance': 150000,
        'color': 'white',
        'image': 'car2'
    },
    {
        'id': 5,
        'type': 'легковые',
        'brand': 'Mitsubishi',
        'name': 'Corolla',
        'year': 2018,
        'price': 2500000,
        'distance': 100000,
        'color': 'red',
        'image': 'car2'
    },
    {
        'id': 6,
        'type': 'внедорожники',
        'brand': 'BMW',
        'name': 'Corolla',
        'year': 2002,
        'price': 2500000,
        'distance': 100000,
        'color': 'yellow',
        'image': 'car3'
    },
    {
        'id': 7,
        'type': 'спортивные',
        'brand': 'Honda',
        'name': 'Corolla',
        'year': 2003,
        'price': 2500000,
        'distance': 100000,
        'color': 'blue',
        'image': 'car1'
    },
    {
        'id': 8,
        'type': 'минивены',
        'brand': 'BYD',
        'name': 'Corolla',
        'year': 2018,
        'price': 2500000,
        'distance': 100000,
        'color': 'purple',
        'image': 'car1'
    },
    {
        'id': 9,
        'type': 'пикапы',
        'brand': 'Mercedes',
        'name': 'Corolla',
        'year': 2018,
        'price': 2500000,
        'distance': 100000,
        'color': 'brown',
        'image': 'car3'
    },
    {
        'id': 10,
        'type': 'легковые',
        'brand': 'Toyota',
        'name': 'Corolla',
        'year': 2018,
        'price': 2500000,
        'distance': 100000,
        'color': 'black',
        'image': 'car2'
    },
    {
        'id': 11,
        'type': 'спортивные',
        'brand': 'Haval',
        'name': 'Corolla',
        'year': 2020,
        'price': 3500000,
        'distance': 50000,
        'color': 'purple',
        'image': 'car1'
    },
    {
        'id': 12,
        'type': 'внедорожники',
        'brand': 'Toyota',
        'name': 'Camri',
        'year': 2022,
        'price': 4000000,
        'distance': 150000,
        'color': 'green',
        'image': 'car2'
    },
    {
        'id': 13,
        'type': 'пикапы',
        'brand': 'Volkswagen',
        'name': 'Polo',
        'year': 2015,
        'price': 12500000,
        'distance': 50000,
        'color': 'gray',
        'image': 'car3'
    },
    {
        'id': 14,
        'type': 'минивены',
        'brand': 'Subaru',
        'name': 'Corolla',
        'year': 2017,
        'price': 3000000,
        'distance': 150000,
        'color': 'white',
        'image': 'car2'
    },
    {
        'id': 15,
        'type': 'легковые',
        'brand': 'Mitsubishi',
        'name': 'Corolla',
        'year': 2011,
        'price': 2500000,
        'distance': 100000,
        'color': 'red',
        'image': 'car3'
    },
    {
        'id': 16,
        'type': 'внедорожники',
        'brand': 'BMW',
        'name': 'Corolla',
        'year': 2016,
        'price': 2500000,
        'distance': 100000,
        'color': 'yellow',
        'image': 'car1'
    },
    {
        'id': 17,
        'type': 'спортивные',
        'brand': 'Audi',
        'name': 'Corolla',
        'year': 2018,
        'price': 2500000,
        'distance': 100000,
        'color': 'blue',
        'image': 'car2'
    },
    {
        'id': 18,
        'type': 'минивены',
        'brand': 'Scoda',
        'name': 'Corolla',
        'year': 2009,
        'price': 2500000,
        'distance': 100000,
        'color': 'purple',
        'image': 'car1'
    },
    {
        'id': 19,
        'type': 'пикапы',
        'brand': 'Ford',
        'name': 'Corolla',
        'year': 2010,
        'price': 2500000,
        'distance': 100000,
        'color': 'brown',
        'image': 'car2'
    },
]